CarolinaCapilla/al-decor

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_flashes.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/puma.rb, config/routes.rb, db/migrate/20200730200352_devise_create_users.rb, db/migrate/20200730200803_add_name_to_users.rb, db/schema.rb, test/models/user_test.rb
Made changes requested in pull request
=> User model

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_fonts.scss, app/views/pages/home.html.erb
I've added a homepage banner.
Created a banner stylesheet.
=> Homepage created, Banner within stylesheets

app/controllers/items_controller.rb, app/models/item.rb, db/migrate/20200730201242_create_items.rb, test/controllers/items_controller_test.rb, test/models/item_test.rb
created item model with item controller with two methods all, create  and new
=> I have finished form item model an controller

app/controllers/items_controller.rb, db/schema.rb
=> if statment inside create method is done

app/views/items/index.html.erb, app/views/items/new.html.erb
=> i have created index and new views for item

app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/controllers/pages_controller.rb, app/models/item.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/items/_form.html.erb, app/views/items/edit.html.erb, app/views/items/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20200804174716_remove_name_from_users.rb, db/schema.rb
Hey guys, a quick recap on this way branch as it ended up being a bit too long.
Added routes and CRUD actions to items controller + views with forms.
Fixed some conflicts with user validations and added authentication for users so only the home + index + show pages will be displayed without a login.
Added link to home to our logo in the navbar.
=> Items controller v2

config/routes.rb
connected the booking routes with items
=> create the booking routes

app/assets/stylesheets/components/_product.scss, app/controllers/bookings_controller.rb, app/controllers/items_controller.rb, app/models/booking.rb, app/models/item.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/items/_form.html.erb, app/views/items/edit.html.erb, app/views/items/index.html.erb, app/views/items/new.html.erb, app/views/items/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_form.html.erb, app/views/shared/_form_booking.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20200805124441_add_booked_to_bookings.rb, db/schema.rb
Hi guys, 
All bookings and items models are working now (crash tested all of them). 
Views and basic navigation has been implemented, still needs front-end as it really basic at the moment.
I have added some extra validations to both models in order to have persistent data stored in our DB.
Still need to find a way to link "all my bookings" to the navbar as we don't have access to @items from _navbar file right now (any ideas?).
Have a look at it and let me know what you think if we are all happy I can start with the Geocode after this one.
=> Items controller v3

app/views/items/index.html.erb
Gonna push to Heroku afterwards.
=> created link between index and show page

app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> added favicon + changed title and footer name

app/assets/stylesheets/pages/_index.scss, app/views/items/index.html.erb
=> Show page v2

.gitignore, app/controllers/reviews_controller.rb, app/models/item.rb, app/models/review.rb, app/views/items/show.html.erb, app/views/reviews/new.html.erb, config/routes.rb, db/migrate/20200807130159_create_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
1- create review model 
2- create new and destroy methods in review controller 
3- concocted to show items page
=> Review model

app/assets/stylesheets/application.scss, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/bookings/index.html.erb, app/views/shared/_form_booking.html.erb, package.json, yarn.lock
Added datepickr gem to change how the date selection looks
=> datepickr implemented to form booking

app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, app/views/items/index.html.erb, app/views/shared/_form_booking.html.erb, config/routes.rb
Hi guys, 
Did some changes to our bookings routes in order to fix the bookings controller method's edit + destroy and it's all working now. 
Have a look :)
=> Bookings controller v2

app/assets/stylesheets/components/_product.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/views/items/index.html.erb, app/views/items/new.html.erb, app/views/items/show.html.erb
Hey.
I've updated the styling of the index and now put all items under their proper categories. 
Also I updated the styling index nav bar.
Photo attached.
=> Updated index page

app/javascript/packs/application.js, app/views/bookings/show.html.erb
Multiply Q of days by price and adds a flat delivery fee of 40 to all deliveries
=> multiplication of days by price and delivery fee

app/controllers/items_controller.rb, app/views/items/index.html.erb
=> fixed index method + conflicts on index page

app/views/items/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_search_button.html.erb
Hi guys! Been playing around with the positioning of the search button, see attached 3 pictures of possible results. 
I can see that the form place-holder and button might be a bit too big and it's not perfectly centred inside the navbar on the first picture, but as we are using bootstrap that was the only way I've found for both having the same size at the same time of being aligned next to each other.
Let me know what you think.
=> moved search button to navbar

app/assets/stylesheets/components/_bookings.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tabs.scss, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
Hi guys, have a look and let me know what you think, nothing too fancy but not too bad (I think) :)
=> Bookings front end

app/views/shared/_search_button.html.erb
Made changes on the search button placeholder
=> changed placeholder on search button

app/views/bookings/edit.html.erb, app/views/bookings/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/items/edit.html.erb, app/views/items/new.html.erb, app/views/reviews/new.html.erb, app/views/shared/_form.html.erb, app/views/shared/_form_booking.html.erb
1- change all btns in all forms 
2- rake the back link to the centre
=> Done from forms

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/views/items/show.html.erb, app/views/pages/home.html.erb
Updated href links to black and hover underscore, added team page on home and added button on show page.
=> Updated navlinks to black, add show page button, added team on homepage
